const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require('playwright-core');

const url = process.env.CHART_TOOLS_URL || 'http://127.0.0.1:18765';
const out = process.env.CHART_TOOLS_OUTPUT || path.resolve('.qa-runtime/chart-tools-20261004');
const key = '000818|2025-12-17|left';

async function main() {
  fs.mkdirSync(out, { recursive: true });
  const { candidate } = await (await fetch(`${url}/api/sample-candidates?key=${encodeURIComponent(key)}`)).json();
  assert.ok(candidate?.trainable, '隔离试用数据中的真实行情样本可训练');
  const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--disable-gpu'] });
  const context = await browser.newContext({ viewport: { width: 1366, height: 900 }, serviceWorkers: 'block' });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  try {
    await page.goto(url, { waitUntil: 'networkidle' });
    await page.waitForFunction(() => state.serverCatalogLoaded);
    await page.locator(`[data-side-action="train"][data-candidate-key="${key}"]`).click();
    await page.waitForFunction(() => state.bars.length === 220 && !state.sampleLoadingKey);
    const canvas = page.locator('#chartCanvas'); await canvas.scrollIntoViewIfNeeded();
    const draw = async (kind, y1, y2) => { await page.locator(`[data-chart-tool="${kind}"]`).click(); const b=await canvas.boundingBox(); await page.mouse.click(b.x+b.width*.4,b.y+y1); await page.mouse.click(b.x+b.width*.65,b.y+y2); };
    await page.locator('#chartMarkLabel').fill('观察支撑');
    await page.locator('#chartMarkReason').fill('真实行情验收标签');
    await draw('support',140,140);
    await page.waitForFunction(() => state.chartMarks.length === 1);
    assert.equal((await page.evaluate(() => state.chartMarks[0].panel)), 'price');
    assert.equal((await page.evaluate(() => state.chartMarks[0].kind)), 'support');
    assert.equal(await page.evaluate(() => state.chartMarks[0].label), '观察支撑');
    await page.locator('#chartMarkLabel').fill(''); await page.locator('#chartMarkReason').fill('');
    await page.locator('#chartMarksToggle').click();
    assert.equal(await page.evaluate(() => state.chartMarksVisible), false);
    await page.locator('#chartMarksToggle').click();
    await page.locator('#chartUndoTool').click();
    assert.equal(await page.evaluate(() => state.chartMarks.length), 0, '撤销移除新标记');
    await page.locator('#chartRedoTool').click();
    assert.equal(await page.evaluate(() => state.chartMarks.length), 1, '重做恢复标记');
    await page.locator('[data-chart-tool="select"]').click();
    const editBox = await canvas.boundingBox();
    const anchor = await page.evaluate(() => {const m=state.chartMarks[0],l=window.__chartDrawLayout;return {x:l.left+(m.a.index-l.firstGlobalIndex+.5)*l.step,y:l.priceTop+(l.high-m.a.value)/(l.high-l.low)*(l.priceBottom-l.priceTop)};});
    const beforeEdit = await page.evaluate(() => state.chartMarks[0].a.value);
    await page.mouse.move(editBox.x+anchor.x,editBox.y+anchor.y); await page.mouse.down();
    await page.mouse.move(editBox.x+anchor.x+12,editBox.y+anchor.y-8,{steps:4}); await page.mouse.up();
    assert.notEqual(await page.evaluate(() => state.chartMarks[0].a.value), beforeEdit, '选择工具可拖动调整标记');
    const panelY = await page.evaluate(() => {const l=window.__chartDrawLayout;return {volume:l.priceBottom+45,macd:l.priceBottom+110,kdj:l.priceBottom+195};});
    await draw('range',110,185);
    await draw('trend',panelY.volume,panelY.volume+12);
    await draw('trend',panelY.macd,panelY.macd+14);
    await draw('trend',panelY.kdj,panelY.kdj+16);
    assert.deepEqual(await page.evaluate(() => state.chartMarks.map(m=>[m.kind,m.panel])), [['support','price'],['range','price'],['trend','volume'],['trend','macd'],['trend','kdj']]);
    const beforeMove = await page.evaluate(() => {
      const mark=state.chartMarks.find(item=>item.kind==='range'), l=window.__chartDrawLayout, a=chartMarkScreenPoint(mark,'a'), b=chartMarkScreenPoint(mark,'b');
      state.chartTool='select';
      return {id:mark.id, a:structuredClone(mark.a), b:structuredClone(mark.b), x:(a.x+b.x)/2, y:(a.y+b.y)/2, rect:document.querySelector('#chartCanvas').getBoundingClientRect().toJSON()};
    });
    await page.evaluate(async start => {
      const canvas=document.querySelector('#chartCanvas'), make=(x,y,type='touch')=>({pointerId:77,pointerType:type,clientX:start.rect.x+x,clientY:start.rect.y+y,currentTarget:{setPointerCapture(){}}});
      beginChartDrag(make(start.x,start.y));
      await new Promise(resolve=>setTimeout(resolve,500));
      if(!chartMarkMove) throw new Error('长按未进入整条标记移动状态');
      moveChartDrag(make(start.x+22,start.y-18));
      endChartDrag({...make(start.x+22,start.y-18),type:'pointerup'});
    }, beforeMove);
    const afterMove = await page.evaluate(id => state.chartMarks.find(item=>item.id===id), beforeMove.id);
    assert.notEqual(afterMove.a.index,beforeMove.a.index,'触屏长按拖动平移整条标记的横向锚点');
    assert.notEqual(afterMove.a.value,beforeMove.a.value,'触屏长按拖动平移整条标记的纵向锚点');
    assert.equal(afterMove.b.index-afterMove.a.index,beforeMove.b.index-beforeMove.a.index,'整条平移保持区间宽度');
    assert.ok(Math.abs((afterMove.b.value-afterMove.a.value)-(beforeMove.b.value-beforeMove.a.value))<1e-8,'整条平移保持区间高度');
    const beforeMouseMove = await page.evaluate(id => {const mark=state.chartMarks.find(item=>item.id===id),a=chartMarkScreenPoint(mark,'a'),b=chartMarkScreenPoint(mark,'b'),rect=document.querySelector('#chartCanvas').getBoundingClientRect();return {id,a:structuredClone(mark.a),b:structuredClone(mark.b),x:(a.x+b.x)/2,y:(a.y+b.y)/2,rect:{x:rect.x,y:rect.y}};},beforeMove.id);
    await page.mouse.move(beforeMouseMove.rect.x+beforeMouseMove.x,beforeMouseMove.rect.y+beforeMouseMove.y); await page.mouse.down();
    await page.mouse.move(beforeMouseMove.rect.x+beforeMouseMove.x+24,beforeMouseMove.rect.y+beforeMouseMove.y+14,{steps:4}); await page.mouse.up();
    const afterMouseMove=await page.evaluate(id=>state.chartMarks.find(item=>item.id===id),beforeMouseMove.id);
    assert.notEqual(afterMouseMove.a.index,beforeMouseMove.a.index,'鼠标在线段主体拖动可平移整条标记');
    assert.equal(afterMouseMove.b.index-afterMouseMove.a.index,beforeMouseMove.b.index-beforeMouseMove.a.index,'鼠标平移保持区间宽度');
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('kline-training-draft')).chartMarks);
    assert.equal(saved.length, 5, '主副图标记均写入训练草稿');
    const savedHistory = await page.evaluate(() => {const d=JSON.parse(localStorage.getItem('kline-training-draft'));return {actions:d.chartMarkActions,history:d.chartMarkHistory};});
    assert.ok(savedHistory.actions.length >= 8, '新建、调整、撤销和重做均留有操作顺序');
    assert.ok(savedHistory.history.length > 0, '撤销历史可随备份恢复');
    await page.locator('#chartInspectTool').click();
    const observedBox = await canvas.boundingBox();
    await page.mouse.move(observedBox.x + observedBox.width * .57, observedBox.y + 130);
    await page.waitForFunction(() => state.chartCursor && document.querySelector('#chartObservation').textContent.includes('O '));
    const readout = await page.locator('#chartObservation').innerText();
    assert.match(readout, /O .*H .*L .*C .*VOL/);
    assert.match(readout, /单位未标明|股|手/, '成交量明确显示单位或缺失说明');
    const tieTarget=await page.evaluate(()=>({x:window.__chartDrawLayout.left+window.__chartDrawLayout.step,y:window.__chartDrawLayout.priceTop+20,index:window.__chartDrawLayout.firstGlobalIndex}));
    await page.mouse.move(observedBox.x+tieTarget.x,observedBox.y+tieTarget.y);
    assert.equal(await page.evaluate(()=>state.chartCursor.index),tieTarget.index,'两根K线等距时稳定取左侧');
    const stableIndex = await page.evaluate(() => state.currentIndex);
    await page.reload({ waitUntil: 'networkidle' });
    await page.waitForFunction(() => state.bars.length === 220);
    assert.equal(await page.evaluate(() => state.chartMarks.length), 5, '刷新后标记恢复');
    assert.equal(await page.evaluate(() => state.currentIndex), stableIndex, '查看与画线不推进训练');
    const [backupDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#exportSessionButton').click()]);
    const backupPath=path.join(out,backupDownload.suggestedFilename()); await backupDownload.saveAs(backupPath);
    const backup=JSON.parse(fs.readFileSync(backupPath,'utf8'));
    assert.equal(backup.chartMarks.length,5,'训练备份包含新标记');
    assert.ok(backup.chartMarkHistory.length>0 && backup.chartMarkActions.length>=8,'训练备份保留撤销记录与动作顺序');
    await page.locator('#backupFileInput').setInputFiles(backupPath);
    await page.waitForFunction(() => state.symbol === '000818' && state.chartMarks.length === 5);
    for(let i=0;i<35;i+=1) await page.locator('#nextButton').click();
    await page.locator('[data-chart-tool="pan"]').click();
    const panBox=await canvas.boundingBox(), offsetBefore=await page.evaluate(()=>state.chartOffset), indexBeforePan=await page.evaluate(()=>state.currentIndex);
    await page.mouse.move(panBox.x+panBox.width*.55,panBox.y+170);await page.mouse.down();await page.mouse.move(panBox.x+panBox.width*.75,panBox.y+170,{steps:5});await page.mouse.up();
    assert.ok(await page.evaluate(()=>state.chartOffset)>offsetBefore,'平移模式可调整历史视窗');
    assert.equal(await page.evaluate(()=>state.currentIndex),indexBeforePan,'平移不推进训练');
    for (const width of [1366, 390]) {
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
      await page.waitForTimeout(250);
      await page.locator('#chartCanvas').scrollIntoViewIfNeeded();
      await page.locator('#chartInspectTool').click();
      const rect = await page.locator('#chartCanvas').boundingBox();
      await page.mouse.move(rect.x + rect.width * .57, rect.y + 132);
      await page.waitForTimeout(100);
      assert.ok((await page.locator('#chartObservation').innerText()).includes('第'));
      const layout = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: innerWidth }));
      assert.ok(layout.width <= layout.viewport + 1, `页面在${width}px宽度出现横向溢出`);
      await page.screenshot({ path: path.join(out, `chart-tools-${width}.png`), fullPage: true, animations: 'disabled' });
    }
    assert.deepEqual(errors, []);
    const result = { source: '隔离副本中的既有真实行情000818', sample: key, checks: ['主图支撑线与区间、量能/MACD/KDJ趋势线绘制', '鼠标拖动整条标记、触屏长按平移及端点调整', '标记标签和说明、选择调整、显示隐藏、撤销重做', '草稿、训练备份保存与恢复', '自由光标真实K线读数与等距取左', '查看和平移不推进训练', '1366px和390px无横向溢出'], readout, errors, screenshots: out };
    fs.writeFileSync(path.join(out, 'chart-tools-result.json'), JSON.stringify(result, null, 2));
    console.log(JSON.stringify(result, null, 2));
  } finally { await context.close(); await browser.close(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
